version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/Adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception

  # ftp:
  #   build: ./requirements/bonus/FTP
  #   container_name: ftp
  #   restart: always
  #   ports:
  #     - "21:21"
  #   networks:
  #     - inception

  # website:
  #   build: ./requirements/bonus/WebSites
  #   container_name: website
  #   restart: always
  #   ports:
  #     - "8000:80"
  #   networks:
  #     - inception

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge
