version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge
